const CourseCategories = [
  {
    id: 1,
    category: "backend",
    image: "images/python.png",
    chap: "12 Chap",
    duration: "18.5 Hours",
    title: "Python Fundamentals",
    writer: "Ercan Erkalkan",
  },
  {
    id: 2,
    category: "frontend",
    image:"images/angular.png",
    chap:"Chapters",
    duration:"Duration",
    title:"Angular",
    writer:"Given By..",
  },
  {
    id: 3,
    category: "web design",
    image:"images/css.png",
    chap:"Chapters",
    duration:"Duration",
    title:"HTML - CSS",
    writer:"Given By..",
  },
  {
    id: 4,
    category: "programming",
    image:"images/java.png",
    chap:"Chapters",
    duration:"Duration",
    title:"Java",
    writer:"Given By..",
  },
  {
    id: 5,
    category: "frontend",
    image:"images/javascript.png", 
    chap:"Chapters",
    duration:"Duration",
    title:"JavaScript",
    writer:"Given By..",
  },
  {
    id: 6,
    category: "backend",
    image:"images/node.png",
    chap:"Chapters",
    duration:"Duration",
    title:"Node Js",
    writer:"Given By..",
  },
  {
    id: 7,
    category: "frontend",
    image:"images/react.png",
    chap:"Chapters",
    duration:"Duration",
    title:"React Js",
    writer:"Given By..",
  },
  {
    id: 8,
    category: "web design",
    image:"images/shop.png",
    chap:"Chapters",
    duration:"Duration",
    title:"Photoshop",
    writer:"Given By..",
  },
  {
    id: 9,
    category: "frontend",
    image:"images/vue.png",
    chap:"Chapters",
    duration:"Duration",
    title:"Vue Js",
    writer:"Given By..",
  },
  {
    id: 10,
    category: "algorithm",
    image:"images/algorithm.png",
    chap:"Chapters",
    duration:"Duration",
    title:"Algorithm",
    writer:"Given By..",
  },
  {
    id: 11,
    category: "math",
    image:"images/math.png",
    chap:"Chapters",
    duration:"Duration",
    title:"Mathematics",
    writer:"Alan Turing",
  },
  {
    id: 12,
    category: "network",
    image:"images/network.png",
    chap:"Chapters",
    duration:"Duration",
    title:"Network Basics",
    writer:"Vedat Topuz",
  },
  {
    id: 13,
    category: "api",
    image:"images/api.png",
    chap:"Chapters",
    duration:"Duration",
    title:"What is an API?",
    writer:"given by",
  },
  {
    id: 10,
    category: "algorithm",
    image:"images/algorithm2.png",
    chap:"Chapters",
    duration:"Duration",
    title:"What is an Algorithm?",
    writer:"Fatih Kazdal",
  },
];

export default CourseCategories;
