const BlogCategories = [
  {
id:1,
category:"algorithm",
writer:"Ercan Erkalkan",
sphere:"Computer Science",
title:"Typescript is Not New",
image:"/images/typescript.png",
writerImage:"/images/ercan.png",
date:"02 June 2022",
  },
  {
id:2,
category:"network",
writer:"Vedat Topuz",
sphere:"Artificial Intelligence",
title:"We Can Handle Difficulties",
image:"/images/artificial.png",
writerImage:"/images/vedat.png",
date:"14 February 2023",
  },
  {
id:3,
category:"frontend",
writer:"Rahman Coban",
sphere:"FrontEnd",
title:"React Has Been Evolved",
image:"/images/react2.png",
writerImage:"/images/rahim.png",
date:"21 March 2021",
  },
  {
id:4,
category:"programming",
writer:"Abdullah Seis",
sphere:"Frontend",
title:"We Work Harder",
image:"/images/front.png",
writerImage:"/images/abdullah.png",
date:"23 July 2020",
  },
  {
id:5,
category:"network",
writer:"Can Eksioglu",
sphere:"Network",
title:"Fiber is New Hit",
image:"/images/fiber.png",
writerImage:"/images/can.png",
date:"17 April 2020",
  },
  {
id:6,
category:"web design",
writer:"Jerry Seinfeld",
sphere:"New Technologies",
title:"Tech and Comedy",
image:"/images/tech.png",
writerImage:"/images/jerry.png",
date:"02 June 2022",
  },
  {
id:7,
category:"backend",
writer:"Sheldon",
sphere:"Sensorium",
title:"I am a Genius",
image:"/images/intelligence.png",
writerImage:"/images/sheldon.png",
date:"02 June 2022",
  },
  {
id:8,
category:"math",
writer:"Jennifer Lawr",
sphere:"Film Industry",
title:"New Equipments Made",
image:"/images/film.png",
writerImage:"/images/jeni.png",
date:"02 June 2022",
  },
  {
id:9,
category:"api",
writer:"Joey Tribbiani",
sphere:"Sitcom and Internet",
title:"We used to laugh a lot",
image:"/images/sitcom.png",
writerImage:"/images/joe.png",
date:"22 September 1994",
  },
]

export default BlogCategories;
